Repository EGC-zambrano/decide-part-zambrano, pull requests merged in 2023-12, with the labels that each got.

#34 Feature/login GitHub
  decide/authentication/static/auth/style.css
  decide/authentication/templates/authentication/login.html
  decide/authentication/test-selenium.py
  decide/authentication/urls.py
  decide/decide/settings.py
  requirements.txt
Labels: enhancement

#32 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, High priority

#44 Feature/opinions
  decide/booth/admin.py
  decide/booth/form.py
  decide/booth/migrations/0001_initial.py
  decide/booth/models.py
  decide/booth/static/booth/style.css
  decide/booth/templates/booth/opinions.html
  decide/booth/templates/booth/voting-list.html
  decide/booth/test-selenium.py
  decide/booth/tests.py
  decide/booth/urls.py
  decide/booth/views.py
Labels: enhancement, Medium priority

#26 Feature/white voting
  decide/booth/templates/booth/booth.html
  decide/voting/migrations/0007_questionoption_hidden.py
  decide/voting/migrations/0008_voting_blank_vote.py
  decide/voting/migrations/0009_remove_voting_blank_vote.py
  decide/voting/migrations/0010_question_voteblank.py
  decide/voting/models.py
  decide/voting/tests.py
Labels: enhancement, High priority

#41 Feature/recaptcha
  decide/authentication/forms.py
  decide/authentication/templates/authentication/login.html
  decide/authentication/templates/authentication/register.html
  decide/authentication/test-selenium.py
  decide/authentication/tests.py
  decide/authentication/views.py
  decide/booth/test-selenium.py
  decide/decide/settings.py
  decide/manage.py
  requirements.txt
Labels: enhancement

#45 Feature/email after registration
  decide/authentication/admin.py
  decide/authentication/migrations/0001_initial.py
  decide/authentication/models.py
  decide/authentication/test-selenium.py
  decide/authentication/tests.py
  decide/authentication/urls.py
  decide/authentication/views.py
  decide/booth/static/booth/style.css
  decide/booth/static/homepage/homepage.css
  decide/booth/templates/booth/homepage.html
  decide/booth/test-selenium.py
  decide/booth/views.py
  requirements.txt
Labels: enhancement, Medium priority

#52 Test/locust
  loadtest/gen_census.py
  loadtest/locustfile.py
  requirements.txt
Labels: enhancement, Medium priority

#53 Workflow/render fix
  decide/authentication/views.py
  decide/local_settings.deploy.py
Labels: enhancement, High priority

#56 Feature/boolean voting
  decide/store/views.py
  decide/voting/migrations/0011_alter_question_question_type.py
  decide/voting/models.py
  decide/voting/tests.py
Labels: enhancement, Medium priority

#58 Feature/multivoting visualization
  decide/base/static/base/style.css
  decide/booth/static/booth/style.css
  decide/booth/templates/booth/booth.html
  decide/booth/templates/booth/voting-list.html
  decide/booth/test-selenium.py
  decide/booth/views.py
Labels: enhancement, High priority

#61 Feature/priority voting
  decide/booth/templates/booth/booth.html
  decide/mixnet/mixcrypt.py
  decide/store/migrations/0006_voteoption_p.py
  decide/store/models.py
  decide/store/serializers.py
  decide/store/tests.py
  decide/store/views.py
  decide/voting/migrations/0006_remove_questionoption_question_type_and_more.py
  decide/voting/migrations/0007_alter_question_question_type.py
  decide/voting/migrations/0012_merge_20231217_1712.py
  decide/voting/models.py
  decide/voting/tests.py
Labels: enhancement, Medium priority

#71 Bugfix: Voting filters
  decide/booth/templates/booth/voting-list.html
Labels: bug, High priority

#69 Feature/census csv
  decide/census/admin.py
  decide/census/templates/admin/census/census/change_list.html
  decide/census/templates/admin/import_census.html
  decide/census/tests.py
Labels: enhancement, Medium priority

#72 Feature/restaurar contraseña
  decide/authentication/templates/authentication/login.html
  decide/authentication/templates/authentication/password_reset.html
  decide/authentication/templates/authentication/password_reset_complete.html
  decide/authentication/templates/authentication/password_reset_confirm.html
  decide/authentication/templates/authentication/password_reset_done.html
  decide/authentication/test-selenium.py
  decide/authentication/tests.py
  decide/authentication/urls.py
  decide/authentication/views.py
  decide/decide/settings.py
  requirements.txt
Labels: enhancement, Medium priority

#76 Feature/priority voting visualization
  decide/booth/static/booth/style.css
  decide/booth/templates/booth/booth.html
Labels: enhancement, High priority

#80 fix: render ci configuration
  .github/workflows/render.yml
Labels: bug
